### update grocer
PUT http://localhost:8000/grocer/18

Content-Type: application/json
{
    "grocerName": "Prueba edicion de cliente",
    "ownerName": "Prueba uno",
    "documentType": "cedula de ciudadania",
    "documentId": 10323523224,
    "cellphone": 3456778993,
    "phone": 5678905,
    "email": "prueba@gmail.com",
    "address": "CRA 27 # 15-15, Bogota, Colombia",
    "neighborhood": "Suba",
    "locality" : "Suba",
    "zone" : 1,
    "latitude": 4.15,
    "longitude": -7.68,
    "sellerCreator": 30,
    "addressAdditionalInfo": "En la esquina"
}

### get grocer by id
GET  http://localhost:8000/grocer/18

### get all grocers
GET  http://localhost:8000/grocers/0&5&1&1&2021-07-22&2021-07-19&1

### create new grocer
POST http://localhost:8000/grocer/create
Content-Type: application/json

{
    "grocerName": "Prueba cinco",
    "ownerName": "Prueba cinco",
    "documentType": "cedula de ciudadania",
    "documentId": 123234234203,
    "cellphone": 3124325344,
    "phone": 5678905,
    "email": "nice@example.com",
    "address": "CRA 35 # 15-15, Bogota, Colombia",
    "neighborhood": "Suba",
    "locality" : "Suba",
    "zone" : 1,
    "latitude": 4.15,
    "longitude": -7.68,
    "sellerCreator": 30,
    "addressAdditionalInfo": "En la esquina"
}

### delete grocer
DELETE http://localhost:8000/grocer/1
### asign grocer level
PUT http://localhost:8000/grocerLevel/18