### update grocer
PUT http://localhost:8000/grocer/18

Content-Type: application/json
{
    "grocerName": "Prueba edicion de cliente",
    "ownerName": "Prueba uno",
    "documentType": "cedula de ciudadania",
    "documentId": 10323523224,
    "cellphone": 3456778993,
    "phone": 5678905,
    "email": "prueba@gmail.com",
    "address": "CRA 27 # 15-15, Bogota, Colombia",
    "neighborhood": "Suba",
    "locality" : "Suba",
    "zone" : 1,
    "latitude": 4.15,
    "longitude": -7.68,
    "sellerCreator": 30,
    "addressAdditionalInfo": "En la esquina"
}

### get grocer by id
GET  http://localhost:8000/grocer/18

### get all grocers
GET  http://localhost:8000/grocers/{"filterId" : "1", "sellerId": "2", "zone" : "1","level": "1","dateFrom" : "2","dateTo": "2"}

### create new grocer
POST http://localhost:8000/grocer/create
Content-Type: application/json

{
    "grocerName": "Prueba error",
    "ownerName": "Prueba error",
    "documentType": "cedula de ciudadania",
    "documentId": 1234234203,
    "cellphone": 2999999999,
    "phone": 5678905,
    "email": "good@example.com",
    "address": "CRA 45 # 15-15, Bogota, Colombia",
    "neighborhood": "Suba",
    "locality" : "Suba",
    "zone" : 1,
    "latitude": 4.15,
    "longitude": -7.68,
    "sellerCreator": 30,
    "addressAdditionalInfo": "En la esquina"
}

### delete grocer
DELETE http://localhost:8000/grocer/1