POST http://localhost:8000/grocer/create
Content-Type: application/json

{
    "grocerName": "SOMe name",
    "ownerName": "owner name",
    "documentType": "cedula de ciudadania",
    "documentId": 1034567898,
    "cellphone": 3456778990,
    "phone": 5678909,
    "email": "mail@mailk.com",
    "address": "CRA 15 # 15-15, Bogota, Colombia",
    "neighborhood": "Suba",
    "latitude": 4.15,
    "longitude": -7.68,
    "sellerCreator": "Asesor Premium",
    "moreAddtionalInformation": "En la esquina"
}