## Edicion de cliente
PUT  http://localhost:8000/grocer/20
Content-Type: application/json

{
    "grocerName": "Edicion Prueba",
    "ownerName": "Prueba dos",
    "documentType": "cedula de ciudadania",
    "documentId": 10323523224,
    "cellphone": 3456778993,
    "phone": 5678905,
    "email": "prueba@gmail.com",
    "address": "CRA 17 # 15-15, Bogota, Colombia",
    "neighborhood": "Suba",
    "locality" : "Suba",
    "zone" : 1,
    "latitude": 4.15,
    "longitude": -7.68,
    "sellerCreator": 30,
    "addressAdditionalInfo": "En la esquina"
}

## buscar un cliente por id
GET  http://localhost:8000/grocer/1

## Buscar a todos los Clientes
GET  http://localhost:8000/grocers

## creando nuevo cliente
POST http://localhost:8000/grocer/create
Content-Type: application/json

{
    "grocerName": "Prueba",
    "ownerName": "Prueba dos",
    "documentType": "cedula de ciudadania",
    "documentId": 10323523224,
    "cellphone": 3456778993,
    "phone": 5678905,
    "email": "prueba@gmail.com",
    "address": "CRA 17 # 15-15, Bogota, Colombia",
    "neighborhood": "Suba",
    "locality" : "Suba",
    "zone" : 1,
    "latitude": 4.15,
    "longitude": -7.68,
    "sellerCreator": 30,
    "addressAdditionalInfo": "En la esquina"
}

## Eliminacion de cliente
DELETE http://localhost:8000/grocer/1